Bookstore: add reducers and actions
HenaryKhuraijam/bookstore-react pull request #2
Opened 2023-09-27 14:34 UTC by HenaryKhuraijam

### Bookstore: add reducers and actions
- Added Redux Toolkit (npm install react-redux @reduxjs/toolkit).
- Created a directory that will contain all your Redux logic 
- Configured a Redux store
- Defined a slice of state for books that: Add and Remove books
- Defined a slice of state for categories that: array of categories and reducer that checks the status

2023-09-27 16:02 UTC, frank1738 requested changes
Hi @HenaryKhuraijam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ File structure followed ducks pattern👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 16:02 UTC, ghost commented on src/redux/books/books.js
> +  }
- [ ] 👋 Hey there! 📚 It's awesome to see your work on the bookstore project! 📖📚

Just a quick heads-up 🚀: In our project requirements, we're aiming to use createSlice from Redux Toolkit because it simplifies and streamlines our Redux code, making it more maintainable and efficient. 🛠️✨

By using createSlice, we can eliminate some of the boilerplate code and potential bugs that might crop up with manual action and reducer definitions. 🐛🚫 It also encourages a consistent and scalable approach to managing state in our app. 🔄📦

So, if we could switch over to createSlice, it would not only meet the project requirements but also make our codebase cleaner and easier to work with in the long run. 🧹👌

### Here is an example of a `bookSlice` using `createSlice`

```
// ./src/redux/books/booksSlice.js

import { createSlice } from "@reduxjs/toolkit"

export const booksSlice = createSlice({
  name: "books",
  initialState: {
    books: [],
  },
  reducers: {
    addBook: (state, action) => {
      state.books = [
        ...state.books,
        {
          id: Math.floor(Math.random() * 100),
          title: action.payload.title,
          author: action.payload.author,
        },
      ]
    },
    removeBook: (state, action) => {
      state.books = state.books.filter((book) => book.id !== action.id)
    },
  },
})

export const { addBook, removeBook } = booksSlice.actions

export default booksSlice.reducer

```
Keep up the great work! Feel free to reach out if you have any questions or need assistance with the transition. 🙌🚀😊

2023-09-27 16:02 UTC, ghost commented on src/redux/categories/categories.js
> +export default checkStatusReducer;
- [ ] Kindly also follow the same approach and create a `slice` for your `categories`

2023-09-28 06:17 UTC, HenaryKhuraijam commented on src/redux/categories/categories.js
> +export default checkStatusReducer;
Done

2023-09-28 06:34 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @HenaryKhuraijam,

✔️ Implementation of reducers using `createSlice`

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 06:39 UTC, merged